ALTER TABLE "RazorpaySettlement" ALTER COLUMN "amount" TYPE DOUBLE PRECISION;

ALTER TABLE "RazorpaySettlementItem" ALTER COLUMN "amount" TYPE DOUBLE PRECISION;
ALTER TABLE "RazorpaySettlementItem" ALTER COLUMN "fee" TYPE DOUBLE PRECISION;
ALTER TABLE "RazorpaySettlementItem" ALTER COLUMN "tax" TYPE DOUBLE PRECISION;
