ALTER TABLE "Invoice" ADD COLUMN "fee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "discount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Invoice" ADD COLUMN "walletCredit" DOUBLE PRECISION NOT NULL DEFAULT 0;
