ALTER TABLE "OrganizerLedgerTx" ADD COLUMN "commissionGstAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "OrganizerLedgerTx" ADD COLUMN "tcsAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VenueLedgerTx" ADD COLUMN "commissionGstAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VenueLedgerTx" ADD COLUMN "tcsAmount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "VenueLedgerTx" ADD COLUMN "bookingId" TEXT;
