-- No DDL change: `@default(cuid())` on CareerJob.id is generated by
-- Prisma Client at insert time, not a database-level DEFAULT clause, so
-- there's no column/constraint to alter. This migration exists only to
-- keep the migration history in sync with schema.prisma. Existing rows
-- (slug-based ids like "job-backend-engineer") are untouched; only new
-- rows created after this change get a cuid.
SELECT 1;
